Improve wording and fix tiny typos (intro & chapter 1)
CUQI-DTU/CUQI-Book pull request #39
Opened 2024-08-07 16:55 UTC by chaozg

I found some tiny typos along my reading so I corrected them : )

2024-08-08 09:47 UTC, amal-ghamdi requested changes
Hi @chaozg, many thanks for your edits. This is really helpful! I added two small comments

2024-08-08 13:21 UTC, chaozg commented on chapter01/Intro_example.ipynb
> +    "A Common choice for simplicity is the zero mean isotropic Gaussian prior, defined as\n",
updated to `A Common choice for simplicity is the zero mean Gaussian prior where the components are independent and identically distributed (i.i.d.):`

2024-08-08 13:22 UTC, chaozg commented on chapter01/Intro_example.ipynb
> +    "    - Plot the PDF of the data distribution `b_mult` given a different value of `x=np.array([0.4, 0.3])`. What can we say about the noise ratio to the exact data in this case, and why?\n",
I see and just changed it back to what it was

2024-08-09 14:21 UTC, amal-ghamdi approved these changes
Thanks @chaozg! LGTM

2024-08-12 07:39 UTC, merged