Update distribution notebook
CUQI-DTU/CUQI-Book pull request #65
Opened 2024-09-01 20:55 UTC by chaozg

fixed #64 

So far, I have corrected some tiny typos in `chapter0A/B01_Distributions.ipynb`. 

However, the manually added table content is not working either in vscode or on the webpage.

2024-09-03 13:32 UTC, amal-ghamdi reviewed
Thank you @chaozg for the updates! I did not take a thorough look yet. May I ask you please if you can remove the output of the notebook. Our convention for now is that for all the book notebooks, we do not add the output (except the ones for CIL, fenics and PyTorch for now). It will also make it easier to do the review and spot what changed. 

Many thanks!

2024-09-03 14:00 UTC, amal-ghamdi requested changes
Hi @chaozg, many thanks for the updates! I made a few comments, feel free to incorporate as you see fit.

2024-09-03 17:20 UTC, chaozg commented on chapter0A/B01_Distributions.ipynb
> +    "y_samples.plot([100,200,300], marker='o')"
Done as suggested

2024-09-03 18:09 UTC, amal-ghamdi commented on chapter0A/B01_Distributions.ipynb
> +    "y_samples.plot([100,200,300], marker='o')"
👍

2024-09-04 07:15 UTC, jakobsj approved these changes
LGTM, thanks!

2024-09-04 08:40 UTC, merged